
package com.ws.client.binary;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BinaryWebService", targetNamespace = "http://rest.ws.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BinaryWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uploadData", targetNamespace = "http://rest.ws.com/", className = "com.ws.client.binary.UploadData")
    @ResponseWrapper(localName = "uploadDataResponse", targetNamespace = "http://rest.ws.com/", className = "com.ws.client.binary.UploadDataResponse")
    public String uploadData(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "downloadData", targetNamespace = "http://rest.ws.com/", className = "com.ws.client.binary.DownloadData")
    @ResponseWrapper(localName = "downloadDataResponse", targetNamespace = "http://rest.ws.com/", className = "com.ws.client.binary.DownloadDataResponse")
    public byte[] downloadData(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
