
package com.ws.client.binary;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BinaryWebServiceService", targetNamespace = "http://rest.ws.com/", wsdlLocation = "http://localhost:8080/webservice/BinaryWebService?wsdl")
public class BinaryWebServiceService
    extends Service
{

    private final static URL BINARYWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException BINARYWEBSERVICESERVICE_EXCEPTION;
    private final static QName BINARYWEBSERVICESERVICE_QNAME = new QName("http://rest.ws.com/", "BinaryWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/webservice/BinaryWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BINARYWEBSERVICESERVICE_WSDL_LOCATION = url;
        BINARYWEBSERVICESERVICE_EXCEPTION = e;
    }

    public BinaryWebServiceService() {
        super(__getWsdlLocation(), BINARYWEBSERVICESERVICE_QNAME);
    }

    public BinaryWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BINARYWEBSERVICESERVICE_QNAME, features);
    }

    public BinaryWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, BINARYWEBSERVICESERVICE_QNAME);
    }

    public BinaryWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BINARYWEBSERVICESERVICE_QNAME, features);
    }

    public BinaryWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BinaryWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BinaryWebService
     */
    @WebEndpoint(name = "BinaryWebServicePort")
    public BinaryWebService getBinaryWebServicePort() {
        return super.getPort(new QName("http://rest.ws.com/", "BinaryWebServicePort"), BinaryWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BinaryWebService
     */
    @WebEndpoint(name = "BinaryWebServicePort")
    public BinaryWebService getBinaryWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://rest.ws.com/", "BinaryWebServicePort"), BinaryWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BINARYWEBSERVICESERVICE_EXCEPTION!= null) {
            throw BINARYWEBSERVICESERVICE_EXCEPTION;
        }
        return BINARYWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
