
package com.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeWebService", targetNamespace = "http://turcell.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeWebService {


    /**
     * 
     * @param employeeId
     * @return
     *     returns com.ws.client.Employee
     * @throws MyException_Exception
     */
    @WebMethod
    @WebResult(name = "employee", targetNamespace = "")
    @RequestWrapper(localName = "getEmployee", targetNamespace = "http://turcell.com", className = "com.ws.client.GetEmployee")
    @ResponseWrapper(localName = "getEmployeeResponse", targetNamespace = "http://turcell.com", className = "com.ws.client.GetEmployeeResponse")
    public Employee getEmployee(
        @WebParam(name = "employeeId", targetNamespace = "")
        long employeeId)
        throws MyException_Exception
    ;

    /**
     * 
     * @param employee
     */
    @WebMethod
    @RequestWrapper(localName = "insertEmployee", targetNamespace = "http://turcell.com", className = "com.ws.client.InsertEmployee")
    @ResponseWrapper(localName = "insertEmployeeResponse", targetNamespace = "http://turcell.com", className = "com.ws.client.InsertEmployeeResponse")
    public void insertEmployee(
        @WebParam(name = "employee", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<Employee> employee);

}
