
package com.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmployeeWebServiceService", targetNamespace = "http://turcell.com", wsdlLocation = "http://localhost:8080/webservice/EmployeeWebService?wsdl")
public class EmployeeWebServiceService
    extends Service
{

    private final static URL EMPLOYEEWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPLOYEEWEBSERVICESERVICE_EXCEPTION;
    private final static QName EMPLOYEEWEBSERVICESERVICE_QNAME = new QName("http://turcell.com", "EmployeeWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/webservice/EmployeeWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPLOYEEWEBSERVICESERVICE_WSDL_LOCATION = url;
        EMPLOYEEWEBSERVICESERVICE_EXCEPTION = e;
    }

    public EmployeeWebServiceService() {
        super(__getWsdlLocation(), EMPLOYEEWEBSERVICESERVICE_QNAME);
    }

    public EmployeeWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLOYEEWEBSERVICESERVICE_QNAME, features);
    }

    public EmployeeWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, EMPLOYEEWEBSERVICESERVICE_QNAME);
    }

    public EmployeeWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLOYEEWEBSERVICESERVICE_QNAME, features);
    }

    public EmployeeWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmployeeWebService
     */
    @WebEndpoint(name = "EmployeeWebServicePort")
    public EmployeeWebService getEmployeeWebServicePort() {
        return super.getPort(new QName("http://turcell.com", "EmployeeWebServicePort"), EmployeeWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeeWebService
     */
    @WebEndpoint(name = "EmployeeWebServicePort")
    public EmployeeWebService getEmployeeWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://turcell.com", "EmployeeWebServicePort"), EmployeeWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLOYEEWEBSERVICESERVICE_EXCEPTION!= null) {
            throw EMPLOYEEWEBSERVICESERVICE_EXCEPTION;
        }
        return EMPLOYEEWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
